# Generated by Django 5.0.6 on 2024-07-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('Pid', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=40)),
                ('Birth_date', models.DateField()),
                ('Adhar_no', models.IntegerField()),
                ('Pancard_no', models.CharField(max_length=30)),
            ],
        ),
    ]
